FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY . .


RUN dotnet restore "src/Pharmacy.Web/Pharmacy.Web.csproj"


WORKDIR "/src/src/Pharmacy.Web"
RUN dotnet publish "Pharmacy.Web.csproj" -c Release -o /app/publish \
    /p:UseAppHost=false \
    /p:ErrorOnDuplicatePublishOutputFiles=false


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080
ENTRYPOINT ["dotnet", "Pharmacy.Web.dll"]