events {}
http {
    server {
        listen 80;

        # Основной сайт (Интерфейс)
        location / {
            proxy_pass http://web:8080; 
        }

        # API и Swagger
        location /api/ {
            proxy_pass http://api:8080/api/;
        }
        
        location /swagger {
            proxy_pass http://api:8080/swagger;
        }
    }
}