{
 "title": "Мониторинг Аптеки",
 "time": { "from": "2026-04-18T11:28:11.837Z", "to": "2026-04-18T11:29:48.078Z" },
 "panels": [
  {
   "title": "Количество запросов в API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нагрузка на процессор (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_working_set_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}